Add a few tests

diff --git a/asyncproc b/asyncproc
--- a/asyncproc
+++ b/asyncproc
@@ -15,7 +15,7 @@ asyncproc_init() {
     declare -F asyncproc_conf_local &> /dev/null && asyncproc_conf_local || :
 
     mkfifo -m 600 ${ASYNCPROC_INPUT} &> /dev/null || asyncproc_die "Cannot create ${ASYNCPROC_INPUT}"
-    exec 5<>${ASYNCPROC_INPUT}
+    exec 5<>${ASYNCPROC_INPUT} || asyncproc_die "Cannot assign a FD to ${ASYNCPROC_INPUT}"
 }
 
 asyncproc_conf() {
@@ -27,23 +27,34 @@ asyncproc_conf() {
     asyncproc_die_exitcode="13"
     asyncproc_handlers=()
     asyncproc_kill_timeout="16"
-    asyncproc_async_pids=()
+    asyncproc_term_timeout="0"
+    asyncproc_main_pid=$BASHPID
 
-    asyncproc_workers=()
-    asyncproc_exitcodes=()
-    asyncproc_stdouts=()
-    asyncproc_stderrs=()
+    asyncproc_workers=() # all "PID - Commands" in the session
+    asyncproc_exitcodes=() # all "PID - Exit codes" in the session
+    asyncproc_stdouts=() # all "PID - File names with stdout" in the session
+    asyncproc_stderrs=() # all "PID - File names with stderr" in the session 
+
+    asyncproc_last_workers=() # all "PID - Commands" in the current run
+    asyncproc_last_exitcodes=() # all "PID - Exit codes" in the current run
+    asyncproc_last_stdouts=() # all "PID - File names with stdout" in the current run
+    asyncproc_last_stderrs=() # all "PID - File names with stderr" in the current run
+    asyncproc_last_wd_pid="0" # a watchdog for all processes in the current run
 }
 
 asyncproc_exit() {
+    asyncproc_say "Stopping..."
     asyncproc_get_exitcodes "close"
     asyncproc_get_stdouts "close"
     asyncproc_get_stderrs "close"
 
     asyncproc_term_procs ${asyncproc_kill_timeout} ${asyncproc_handlers[*]} &>/dev/null
+    asyncproc_term_procs ${asyncproc_kill_timeout} ${!asyncproc_last_workers[*]} ${asyncproc_last_wd_pid} &>/dev/null
     
-    exec 5>&-
-    rm -f ${ASYNCPROC_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_INPUT}"
+    [[ -L /proc/$$/fd/5 ]] && exec 5>&-
+    if [[ -n "${ASYNCPROC_INPUT}" ]] && [[ -p ${ASYNCPROC_INPUT} ]]; then
+        rm -f ${ASYNCPROC_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_INPUT}"
+    fi
 
     asyncproc_say "Workers: ${asyncproc_workers[*]}"
     asyncproc_say "Exit codes: ${asyncproc_exitcodes[*]}"
@@ -67,19 +78,23 @@ asyncproc_handler_ec_start() {
         asyncproc_say "Ready to receive exit codes at ${ASYNCPROC_HANDLER_EC_INPUT}"
 
         while :; do
-            [[ -p ${ASYNCPROC_HANDLER_EC_INPUT} ]] || asyncproc_die "Cannot read from ${ASYNCPROC_HANDLER_EC_INPUT}"
-            read -u 6 _pid _ec
-            if [[ -n "${_pid}" ]]; then
-                if [[ "${_pid}" = "dump" ]] || [[ "${_pid}" = "close" ]]; then
-                    for _ec_k in ${!_ecs[*]}; do
-                        echo "${_ec_k} ${_ecs[${_ec_k}]}" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
-                        unset _ecs[${_ec_k}]
-                    done
-                    echo "end" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
-                    [[ "${_pid}" = "close" ]] && exit
-                elif [[ ${_pid} -gt 0 ]] && [[ -n "${_ec}" ]] && [[ ${_ec} -ge 0 ]]; then
-                    _ecs[${_pid}]=${_ec}
+            if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -L /proc/$$/fd/5 ]] && [[ -p ${ASYNCPROC_HANDLER_EC_INPUT} ]] && [[ -L /proc/$$/fd/6 ]]; then 
+                read -u 6 _pid _ec
+                if [[ -n "${_pid}" ]]; then
+                    if [[ "${_pid}" = "dump" ]] || [[ "${_pid}" = "close" ]]; then
+                        for _ec_k in ${!_ecs[*]}; do
+                            echo "${_ec_k} ${_ecs[${_ec_k}]}" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
+                            unset _ecs[${_ec_k}]
+                        done
+                        echo "end" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
+                        [[ "${_pid}" = "close" ]] && exit
+                    elif [[ ${_pid} -gt 0 ]] && [[ -n "${_ec}" ]] && [[ ${_ec} -ge 0 ]]; then
+                        asyncproc_handler_ec_add _ecs ${_pid} ${_ec}
+                        declare -F asyncproc_handler_ec_add_local &> /dev/null && asyncproc_handler_ec_add_local _ecs ${_pid} ${_ec} || :
+                    fi
                 fi
+            else
+                asyncproc_die "Cannot read from ${ASYNCPROC_HANDLER_EC_INPUT}"
             fi
         done
     )&
@@ -87,12 +102,16 @@ asyncproc_handler_ec_start() {
     asyncproc_say "Exitcode handler has been started as ${asyncproc_handlers[-1]}"
 }
 
+asyncproc_handler_ec_add() {
+    eval $1[\$2]="\$3"
+}
+
 asyncproc_handler_ec_init() {
     asyncproc_handler_ec_conf
     declare -F asyncproc_handler_ec_conf_local &> /dev/null && asyncproc_handler_ec_conf_local || :
 
     mkfifo -m 600 ${ASYNCPROC_HANDLER_EC_INPUT} &> /dev/null || asyncproc_die "Cannot create ${ASYNCPROC_HANDLER_EC_INPUT}"
-    exec 6<>${ASYNCPROC_HANDLER_EC_INPUT}
+    exec 6<>${ASYNCPROC_HANDLER_EC_INPUT} || asyncproc_die "Cannot assign a FD to ${ASYNCPROC_HANDLER_EC_INPUT}"
 }
 
 asyncproc_handler_ec_conf() {
@@ -100,8 +119,10 @@ asyncproc_handler_ec_conf() {
 }
 
 asyncproc_handler_ec_exit() {
-    exec 6>&-
-    rm -f ${ASYNCPROC_HANDLER_EC_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_HANDLER_EC_INPUT}"
+    [[ -L /proc/$$/fd/6 ]] && exec 6>&-
+    if [[ -n "${ASYNCPROC_HANDLER_EC_INPUT}" ]] && [[ -p ${ASYNCPROC_HANDLER_EC_INPUT} ]]; then
+        rm -f ${ASYNCPROC_HANDLER_EC_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_HANDLER_EC_INPUT}"
+    fi
     asyncproc_say "Exitcode handler has exited"
 }
 
@@ -117,19 +138,22 @@ asyncproc_handler_stdout_start() {
         asyncproc_say "Ready to receive stdouts at ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
 
         while :; do
-            [[ -p ${ASYNCPROC_HANDLER_STDOUT_INPUT} ]] || asyncproc_die "Cannot read from ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
-            read -u 7 _pid _stdout
-            if [[ -n "${_pid}" ]]; then
-                if [[ "${_pid}" = "dump" ]] || [[ "${_pid}" = "close" ]]; then
-                    for _stdout_k in ${!_stdouts[*]}; do
-                        echo "${_stdout_k} \"${_stdouts[${_stdout_k}]}\"" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
-                        unset _stdouts[${_stdout_k}]
-                    done
-                    echo "end" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
-                    [[ "${_pid}" = "close" ]] && exit
-                elif [[ ${_pid} -gt 0 ]] && [[ -n "${_stdout}" ]]; then
-                    _stdouts[${_pid}]="${_stdout}"
+            if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -L /proc/$$/fd/5 ]] && [[ -p ${ASYNCPROC_HANDLER_STDOUT_INPUT} ]] && [[ -L /proc/$$/fd/7 ]]; then
+                read -u 7 _pid _stdout
+                if [[ -n "${_pid}" ]]; then
+                    if [[ "${_pid}" = "dump" ]] || [[ "${_pid}" = "close" ]]; then
+                        for _stdout_k in ${!_stdouts[*]}; do
+                            echo "${_stdout_k} \"${_stdouts[${_stdout_k}]}\"" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
+                            unset _stdouts[${_stdout_k}]
+                        done
+                        echo "end" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
+                        [[ "${_pid}" = "close" ]] && exit
+                    elif [[ ${_pid} -gt 0 ]] && [[ -n "${_stdout}" ]]; then
+                        _stdouts[${_pid}]="${_stdout}"
+                    fi
                 fi
+            else
+               asyncproc_die "Cannot read from ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
             fi
         done
     )&
@@ -142,7 +166,7 @@ asyncproc_handler_stdout_init() {
     declare -F asyncproc_handler_stdout_conf_local &> /dev/null && asyncproc_handler_stdout_conf_local || :
 
     mkfifo -m 600 ${ASYNCPROC_HANDLER_STDOUT_INPUT} &> /dev/null || asyncproc_die "Cannot create ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
-    exec 7<>${ASYNCPROC_HANDLER_STDOUT_INPUT}
+    exec 7<>${ASYNCPROC_HANDLER_STDOUT_INPUT} || asyncproc_die "Cannot assign a FD to ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
 }
 
 asyncproc_handler_stdout_conf() {
@@ -150,8 +174,10 @@ asyncproc_handler_stdout_conf() {
 }
 
 asyncproc_handler_stdout_exit() {
-    exec 7>&-
-    rm -f ${ASYNCPROC_HANDLER_STDOUT_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
+    [[ -L /proc/$$/fd/7 ]] && exec 7>&-
+    if [[ -n "${ASYNCPROC_HANDLER_STDOUT_INPUT}" ]] && [[ -p ${ASYNCPROC_HANDLER_STDOUT_INPUT} ]]; then
+        rm -f ${ASYNCPROC_HANDLER_STDOUT_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_HANDLER_STDOUT_INPUT}"
+    fi
     asyncproc_say "Stdout handler has exited"
 }
 
@@ -167,19 +193,22 @@ asyncproc_handler_stderr_start() {
         asyncproc_say "Ready to receive stderrs at ${ASYNCPROC_HANDLER_STDERR_INPUT}"
 
         while :; do
-            [[ -p ${ASYNCPROC_HANDLER_STDERR_INPUT} ]] || asyncproc_die "Cannot read from ${ASYNCPROC_HANDLER_STDERR_INPUT}"
-            read -u 8 _pid _stderr
-            if [[ -n "${_pid}" ]]; then
-                if [[ "${_pid}" = "dump" ]] || [[ "${_pid}" = "close" ]]; then
-                    for _stderr_k in ${!_stderrs[*]}; do
-                        echo "${_stderr_k} ${_stderrs[${_stderr_k}]}" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
-                        unset _stderrs[${_stderr_k}]
-                    done
-                    echo "end" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
-                    [[ "${_pid}" = "close" ]] && exit
-                elif [[ ${_pid} -gt 0 ]] && [[ -n "${_stderr}" ]]; then
-                    _stderrs[${_pid}]="${_stderr}"
+            if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -L /proc/$$/fd/5 ]] && [[ -p ${ASYNCPROC_HANDLER_STDERR_INPUT} ]] && [[ -L /proc/$$/fd/8 ]]; then
+                read -u 8 _pid _stderr
+                if [[ -n "${_pid}" ]]; then
+                    if [[ "${_pid}" = "dump" ]] || [[ "${_pid}" = "close" ]]; then
+                        for _stderr_k in ${!_stderrs[*]}; do
+                            echo "${_stderr_k} ${_stderrs[${_stderr_k}]}" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
+                            unset _stderrs[${_stderr_k}]
+                        done
+                        echo "end" > ${ASYNCPROC_INPUT} || asyncproc_die "Cannot write to ${ASYNCPROC_INPUT}"
+                        [[ "${_pid}" = "close" ]] && exit
+                    elif [[ ${_pid} -gt 0 ]] && [[ -n "${_stderr}" ]]; then
+                        _stderrs[${_pid}]="${_stderr}"
+                    fi
                 fi
+            else
+                asyncproc_die "Cannot read from ${ASYNCPROC_HANDLER_STDERR_INPUT}"
             fi
         done
     )&
@@ -192,7 +221,7 @@ asyncproc_handler_stderr_init() {
     declare -F asyncproc_handler_stderr_conf_local &> /dev/null && asyncproc_handler_stderr_conf_local || :
 
     mkfifo -m 600 ${ASYNCPROC_HANDLER_STDERR_INPUT} &> /dev/null || asyncproc_die "Cannot create ${ASYNCPROC_HANDLER_STDERR_INPUT}"
-    exec 8<>${ASYNCPROC_HANDLER_STDERR_INPUT}
+    exec 8<>${ASYNCPROC_HANDLER_STDERR_INPUT}|| asyncproc_die "Cannot assign a FD to ${ASYNCPROC_HANDLER_STDERR_INPUT}"
 }
 
 asyncproc_handler_stderr_conf() {
@@ -200,8 +229,10 @@ asyncproc_handler_stderr_conf() {
 }
 
 asyncproc_handler_stderr_exit() {
-    exec 8>&-
-    rm -f ${ASYNCPROC_HANDLER_STDERR_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_HANDLER_STDERR_INPUT}"
+    [[ -L /proc/$$/fd/8 ]] && exec 8>&-
+    if [[ -n "${ASYNCPROC_HANDLER_STDERR_INPUT}" ]] && [[ -p ${ASYNCPROC_HANDLER_STDERR_INPUT} ]]; then
+        rm -f ${ASYNCPROC_HANDLER_STDERR_INPUT} || asyncproc_err "Cannot remove ${ASYNCPROC_HANDLER_STDERR_INPUT}"
+    fi
     asyncproc_say "Stderr handler has exited"
 }
 
@@ -256,7 +287,7 @@ asyncproc_term_procs() {
 asyncproc_get_exitcodes() {
     local _pid _ec
 
-    if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -p ${ASYNCPROC_HANDLER_EC_INPUT} ]]; then
+    if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -L /proc/$$/fd/5 ]] && [[ -p ${ASYNCPROC_HANDLER_EC_INPUT} ]] && [[ -L /proc/$$/fd/6 ]]; then
         echo "$1" > ${ASYNCPROC_HANDLER_EC_INPUT}
         while read -u 5 _pid _ec; do
             if [[ "${_pid}" = "end" ]]; then
@@ -271,7 +302,7 @@ asyncproc_get_exitcodes() {
 asyncproc_get_stdouts() {
     local _pid _stdout
 
-    if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -p ${ASYNCPROC_HANDLER_STDOUT_INPUT} ]]; then
+    if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -L /proc/$$/fd/5 ]] && [[ -p ${ASYNCPROC_HANDLER_STDOUT_INPUT} ]] && [[ -L /proc/$$/fd/7 ]]; then
         echo "$1" > ${ASYNCPROC_HANDLER_STDOUT_INPUT}
         while read -u 5 _pid _stdout; do
             if [[ "${_pid}" = "end" ]]; then
@@ -286,7 +317,7 @@ asyncproc_get_stdouts() {
 asyncproc_get_stderrs() {
     local _pid _stderr
 
-    if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -p ${ASYNCPROC_HANDLER_STDERR_INPUT} ]]; then
+    if [[ -p ${ASYNCPROC_INPUT} ]] && [[ -L /proc/$$/fd/5 ]] && [[ -p ${ASYNCPROC_HANDLER_STDERR_INPUT} ]] && [[ -L /proc/$$/fd/8 ]]; then
         echo "$1" > ${ASYNCPROC_HANDLER_STDERR_INPUT}
         while read -u 5 _pid _stderr; do
             if [[ "${_pid}" = "end" ]]; then
